services:
  - type: static
    name: urban-assist-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://urban-assist-backend.onrender.com/api

